---
- name: Install fish shell and dependencies for fisher.
  become: "{{ ansible_pkg_mgr != 'homebrew' }}"
  ansible.builtin.package:
    name:
      - curl
      - fish
    state: present

- name: Locate fish shell binary.
  ansible.builtin.shell: |
    command -v fish
  register: which_fish
  changed_when: false
  failed_when: false

- name: Add fish as known shell.
  become: true
  ansible.builtin.lineinfile:
    line: "{{ which_fish.stdout }}"
    path: /etc/shells

- name: Make fish default shell.
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ which_fish.stdout }}"
  when: ansible_user_id != "root"

- name: Check for fisher plugin manager.
  ansible.builtin.command: fish -c 'fisher --version'
  register: check_fisher
  changed_when: false
  failed_when: false

- name: Install fisher plugin manager.
  ansible.builtin.command: |
    fish -c "curl -fsSL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
  when: check_fisher.rc != 0
  changed_when: check_fisher.rc != 0
